// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEU7ebQpi1jOxrrBU47WAivVBf-b6dMQs',
    appId: '1:134845785087:web:12c9d06e976e31de423dca',
    messagingSenderId: '134845785087',
    projectId: 'chat-app-67a2a',
    authDomain: 'chat-app-67a2a.firebaseapp.com',
    storageBucket: 'chat-app-67a2a.appspot.com',
    measurementId: 'G-2PJ67J0WCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl9-MUvqdSkTkbQGw8-Kg2T2SNpHhFKS0',
    appId: '1:134845785087:android:163cff34fe5e582d423dca',
    messagingSenderId: '134845785087',
    projectId: 'chat-app-67a2a',
    storageBucket: 'chat-app-67a2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCV2wHGWXRXHW1nR9O924ji2Ti_ZnTp5g',
    appId: '1:134845785087:ios:bda2391f88538a50423dca',
    messagingSenderId: '134845785087',
    projectId: 'chat-app-67a2a',
    storageBucket: 'chat-app-67a2a.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCV2wHGWXRXHW1nR9O924ji2Ti_ZnTp5g',
    appId: '1:134845785087:ios:1204d0aa2f461254423dca',
    messagingSenderId: '134845785087',
    projectId: 'chat-app-67a2a',
    storageBucket: 'chat-app-67a2a.appspot.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
